### ISSUE TITLE
Issue with Vision Database Factlet. Can someone please help me to understand what is going on?

### ISSUE THREAD

**Issue by sujit332** [vision-dbms/vision-databases#1]
Hi,

I have added few new portfolios to Vision database. However, these are not showing up on frontend.  Frontend uses Factlet2 given below. When I run the direct method using Factlet 1, I can see the new portfolios. Can someone please help me to understand the difference between Factlet1 and Factlet 2? Why Factlet 2 is not returning new portfolios?

**Factlet1:

Interface ApplicationWS AccountAll; 

Factlet2:

Interface ApplicationWS 
setApplicationTo: "AccountAll" .
           run;**
------------
setApplicationTo definition:

Interface ApplicationWS  defineMethod: [| setApplicationTo: app| 
:currentApplication <- app; 
^self]
---------
run definition
Interface ApplicationWS  defineMethod: [|run|
!app <- currentApplication else: [namedParameters at: "application"]; 
app isNA ifTrue: [
    ErrorLog post: "No Application Selected" for: ^self with: NA; 
   ]
ifFalse: [
    ^self validateApplication: app .ifTrue: [
        !executionBlock <- [^self send: app asBlock]; 
        ^self runExpression: executionBlock; 
       ]
    ifFalse: [ErrorLog post: "Application Not Defined" for: ^self with: app]; 
   ]; 
ErrorLog displayFullLog; 
]

**Comment by LeslieNewman** [comment]
I am assuming that the AccountAll application does not require any other parameters.  A few questions:

- When you run the Factlet2 version, do you get any output or do you get an error message (or something else)?  
- How are you connecting to the batchvision which is processing the query (e.g., starting a new, private session; using a shared worker )?

One trick I find useful is to add a line to the factlet that display the processId so you know for sure which batchvision is in use.  So Factlet1 above could temporarily be written as:

Interface ApplicationWS AccountAll;
"processId: " print ; GlobalWorkspace Utility processId printNL ;

**Comment by sujit332** [comment]
Thank you very much for your response.

- I do get output when I run Faclet2 version. But, the output is not showing newly added portfolios.
- I am starting a new batchvision session for testing. In same session, I am running two Factlets. First one shows recently added portfolios. Where as the second one does not.

The issue seems to be associated with the "date"  for which the Factlets are getting evaluated. Factlet1 is evaluating for latest date. Where as Factset 2 is executed for some older date. I am digging more to see how the session gets the date.

Below fix worked and I am able to see the recently added portfolios on frontend which uses Factlet2. Still need to find out how the date is set on a daily basis. 

**Interface Global setDateTo: ^date ;

Interface ApplicationWS
setApplicationTo: "AccountAll" .
run;**

Appreciate your response!!.

Thanks
Sujatha

**Comment by LeslieNewman** [comment]
In your new batchvision session, what value do you get when you run _Interface Global date_ ?  The _runExpression:_  method uses this value.  If somehow you saved an old date in that property, you would see the behavior you are currently describing.

**Comment by sujit332** [comment]
To my surprise, Interface Global date is showing old date (7/11/2019) in all environments(PROD,UAT and DEV). Not sure how this Global date variable was set. 

For most of the Factlets, we pass date as a parameter. So, the Factlets generally get evaluated for that specific date parameter. However, Factlet1 and Factlet2 does not take date as an date argument.Looks like   Factlet1 does not use runExpression and Factlet2 does.Factlet2 is getting executed for older date(7/11/2019) and not able to fetch the new portfolios.

That seems to be the reason. When I set it back to current date, the portfolios are visible on frontend.

Thanks for your comments on this issue Leslie. Those were helpful. I will close this issue now.
